Stack Implementation in JS and C#
Luizahf/dataStructures pull request #3
Opened 2019-07-25 18:31 UTC by Luizahf

2019-07-26 00:40 UTC, Pedroophss requested changes
Quase perfeito! apenas comentários

2019-07-26 00:40 UTC, Pedroophss commented on Queue/Queue.cs
> +    class Queue
Esse queue deveria estar aqui?

2019-07-26 00:40 UTC, Pedroophss commented on Stack/Stack.cs
> +            // Sets the Stack attr top
Como revisado no Queue refaça os comentarios no padrão do c#.

2019-07-26 00:40 UTC, Pedroophss commented on Stack/Stack.js
> +// Creates a Node with the data and sets "next" value with null default
Refaça os comentarios no padrão do JSDocs

2019-07-26 00:50 UTC, Luizahf commented on Queue/Queue.cs
> +    class Queue
esse é o arquivo queue, entao sim. não entendi

2019-07-26 01:18 UTC, Pedroophss commented on Queue/Queue.cs
> +    class Queue
mas esse não é o branch do stack?

2019-07-31 14:23 UTC, Pedroophss approved these changes

2019-07-31 14:23 UTC, merged